### ISSUE TITLE
Version 1 Roadmap

### ISSUE THREAD

**Issue by sublayerio** [penderio/autonumber-field#1]
## General

- [ ] Publish demo on surge
- [ ] Publish to npm
- [ ] Cover field demo
